[package]
name = "fzz"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
crossterm = { version = "0.28.1", features = ["use-dev-tty"] }
ratatui = "0.29.0"
rayon = "1.10.0"
